all:
  hosts:
    $BECOME_USER@test_server:
  vars:
    ansible_user: $BECOME_USER
    ansible_become: yes
    ansible_become_method: sudo
    ansible_python_interpreter: "/usr/bin/env python3"
    ansible_become_pass: $BECOME_PASSWORD
