- hosts: all
  vars:
    non_root_docker_users:
      - gener
      - docker-compose
      
  tasks:
    - name: Create docker group
      group:
        name: docker
        state: present
      become: yes

    - name: Add user to the docker group
      user:
        name: "{{ item }}"
        groups: docker
        append: yes
      with_items: "{{ non_root_docker_users }}"
      become: yes

    - name: Add Docker Compose to docker group
      become: true
      tags: compose
      ansible.builtin.shell: |
        usermod -aG docker $USER
        chgrp docker /usr/local/bin/docker-compose
        chmod 750 /usr/local/bin/docker-compose
      # ignore_errors: true



    # sudo usermod -aG docker $USER && sudo chgrp docker /usr/local/bin/docker-compose && sudo chmod 750 /usr/local/bin/docker-compose
